models:
  - name: "ES"
    model_type: "volatility_forecast.model.stes_model.STESModel"
    features: []
  - name: "STES-E&AE&SE"
    model_type: "volatility_forecast.model.stes_model.STESModel"
    features:
      - "LagReturn"
      - "LagAbsReturn"
      - "LagSquaredReturn"
  - name: "STES-E&AE"
    model_type: "volatility_forecast.model.stes_model.STESModel"
    features:
      - "LagReturn"
      - "LagAbsReturn"
  - name: "XGBoost-STES"
    model_type: "volatility_forecast.model.xgboost_stes_model.XGBoostSTESModel"
    features:
      - "LagReturn"
      - "LagSquaredReturn"
      - "LagAbsReturn"
    params:
      max_depth: 3
      learning_rate: 0.1
      n_estimators: 100
      objective: "reg: squared error"

evaluation:
  test_size: 0.2
  random_state: 42

scheduler:
  daily_task_time: "00:05"
  recalibration_day: "sun"